name 'pulledpork'
maintainer 'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license 'Apache-2.0'
description 'Installs and Configures the Snort IDS ruleset updater Pulled Pork'
version '3.0.1'

supports 'debian', '>= 7.0'
supports 'ubuntu', '>= 12.04'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'amazon'
supports 'oracle'

depends 'ark'

source_url 'https://github.com/sous-chefs/pulledpork'
issues_url 'https://github.com/sous-chefs/pulledpork/issues'
chef_version '>= 12.0'
